import test from 'node:test';import assert from 'node:assert/strict';import {BoxGeometry,Matrix4} from 'three';
import {assemblyOrder,paginateGuideEntries} from '../src/assembly-order.mjs';
import {guideNotices} from '../src/guide-layout.mjs';
function box(id,x,y=0,z=0,size=[10,10,10]){const g=new BoxGeometry(...size);g.translate(x,y,z);return {id,vertices:new Float32Array(g.attributes.position.array),triangles:new Uint32Array(g.index.array)};}
test('scrambled IDs and list order produce connected steps without renumbering',()=>{const parts=[box('99',30),box('7',0),box('42',20),box('1',10)],before=parts.map(p=>p.id),plan=assemblyOrder(parts);assert.equal(plan.components.length,1);const built=new Set();for(const step of plan.steps){if(built.size)assert.ok(step.contacts.some(i=>built.has(i)));built.add(step.index);}assert.deepEqual(parts.map(p=>p.id),before);assert.equal(new Set(plan.order).size,4);assert.ok(plan.steps[1].index!==1,'input order is not treated as the assembly order');});
test('each disconnected component starts explicitly without fabricated contacts',()=>{const plan=assemblyOrder([box('1',0),box('2',10),box('3',100),box('4',110)]);assert.equal(plan.components.length,2);assert.deepEqual(plan.steps.map(s=>s.isStart),[true,false,true,false]);assert.deepEqual(plan.steps[2].contacts,[]);});
test('contact detection and bottom-up seed selection use assembly poses',()=>{const parts=[box('upper',0,0,20),box('base',200,0,0,[30,30,10]),box('middle',0,0,10)];parts[1].assemblyMatrix=new Matrix4().makeTranslation(-200,0,0).toArray();const plan=assemblyOrder(parts);assert.equal(plan.components.length,1);assert.deepEqual(plan.order,[1,2,0]);assert.deepEqual(plan.steps[2].contacts,[2]);});
test('a declared model-up axis controls the lower assembly starting point',()=>{const parts=[box('top',0,-20),box('middle',0,-10),box('base',0,0,0,[30,10,30])],plan=assemblyOrder(parts,{upDirection:[0,-1,0]});assert.deepEqual(plan.order,[2,1,0]);assert.throws(()=>assemblyOrder(parts,{upDirection:[0,0,0]}),/Oben-Richtung/);});
test('assembly geometry excludes optional detachable support fins',()=>{const parts=[{...box('1',0),supports:{meshes:[box('fin',50,0,0,[100,1,1])]}},box('2',100)];assert.equal(assemblyOrder(parts).components.length,2);});
test('empty and malformed graph inputs are handled explicitly',()=>{assert.deepEqual(assemblyOrder([]).order,[]);assert.throws(()=>assemblyOrder([box('1',0)],{neighbors:[[1]]}),/Montagenachbarschaft/);});
test('long notices paginate without losing or clipping content',()=>{const text='Ein ausführlicher Hinweis. '.repeat(160),pages=paginateGuideEntries([{part:'1',text}],{maxLines:12,lineLength:50});assert.ok(pages.length>3);assert.equal(pages.flat().map(p=>p.text).join(''),text);assert.ok(pages.every(page=>page.reduce((sum,p)=>sum+Math.ceil(p.text.length/50)+1,0)<=12));});
test('guide notices preserve support limits, unresolved marks and separate groups',()=>{const parts=[{...box('1',0),supportNotice:'Durchhang prüfen',supports:{warnings:['Fins reichen hier nicht','Durchhang prüfen']},plannedMarkIssue:'Keine sichere Schriftfläche'},{...box('2',100),mark:{text:'ALT'}}],entries=guideNotices(parts,assemblyOrder(parts)),texts=entries.map(p=>p.text);assert.ok(texts.some(t=>t.includes('2 getrennte Kontaktgruppen')));assert.equal(texts.filter(t=>t==='Durchhang prüfen').length,1);assert.ok(texts.includes('Fins reichen hier nicht'));assert.ok(texts.includes('Keine sichere Schriftfläche'));assert.ok(texts.some(t=>t.includes('ALT')&&t.includes('2')));});
test('joined fin-warning summaries do not repeat their individual warnings',()=>{const warnings=['Unversorgten Überhang prüfen.','Finne passt nicht auf die Druckplatte.'],base=box('1',0),part={...base,supportNotice:warnings.join(' '),supports:{warnings}},plan=assemblyOrder([part]);assert.deepEqual(guideNotices([part],plan).map(p=>p.text),warnings);part.supportNotice='Drucklage wurde erhalten. '+warnings.join(' ');assert.deepEqual(guideNotices([part],plan).map(p=>p.text),['Drucklage wurde erhalten.',...warnings]);});
test('identical notices group all affected IDs without losing individual values or user notes',()=>{const common='Überhänge müssen weiter geprüft werden.',parts=[1,2,3].map((id,i)=>({...box(String(id),i*10),supports:{warnings:[common,`Offene Fläche: ${id} mm²`]},note:'Zuerst trocken anpassen.'})),entries=guideNotices(parts,assemblyOrder(parts)),group=entries.find(e=>e.text===common);assert.deepEqual(group.parts,['1','2','3']);assert.equal(entries.filter(e=>e.text===common).length,1);for(const part of parts){for(const text of part.supports.warnings)assert.ok(entries.some(e=>e.text===text&&e.parts.includes(part.id)));assert.ok(entries.some(e=>e.category==='user-note'&&e.parts.length===1&&e.parts[0]===part.id&&e.text===part.note));}assert.equal(entries.filter(e=>e.category==='user-note').length,3);});
