import test from 'node:test';import assert from 'node:assert/strict';
import {buildConnectorGuide} from '../src/connector-guide.mjs';
import {connectorExportItems,connectorShoppingText} from '../src/connector-export.mjs';
const parts=[{id:'1'},{id:'2'}];
function fixture(){const connection={id:'1-2',parentId:'1',childId:'2',status:'computed',positions:[[0,0,0],[20,0,0]],normal:[0,0,1],pin:{source:'purchased',standard:'DIN 6325',diameter:3,length:10,quantity:2,endClearance:2},hole:{diameter:3.3,depthParent:7,depthChild:7,wallMargin:1},insertion:{direction:[0,0,-1],approachDistance:14,checked:false,scope:'pair',obstacleIds:[]}};return {connections:[connection],pins:[1,2].map(i=>({id:`1-2-P${i}`,connectionId:'1-2',source:'purchased',auxiliary:true,diameter:3,length:10})),order:[0,1]};}
test('purchased pins have a BOM and centered 2 mm end clearance, without fictitious STL files',()=>{const plan=fixture(),guide=buildConnectorGuide(parts,plan.connections,plan);assert.equal(guide.pinFiles.length,0);assert.equal(guide.purchasedPins.length,2);assert.equal(guide.billOfMaterials[0].quantity,2);assert.equal(guide.billOfMaterials[0].source,'purchased');assert.match(guide.billOfMaterials[0].label,/DIN 6325/);assert.deepEqual(guide.steps[1].views.points[0].pinEnds,[[0,0,-5],[0,0,5]]);assert.deepEqual(guide.steps[1].views.points[0].parentHole.bottom,[0,0,-7]);assert.match(guide.steps[1].instruction,/5 mm.*2 mm/);assert.equal(guide.steps[1].completeInsertionVerified,false);});
test('hardware exporter excludes purchased bodies even if legacy geometry is attached',()=>{const plan=fixture();plan.pins[0].vertices=[0,0,0];plan.pins[0].triangles=[0,0,0];const output=connectorExportItems(plan);assert.equal(output.printablePins.length,0);assert.equal(output.purchasedPins.length,2);assert.equal(output.shoppingList[0].quantity,2);assert.match(connectorShoppingText(output.shoppingList),/2 Zylinderstifte DIN 6325, Ø 3 × 10 mm/);});
test('mixed printed and purchased quantities and sources cannot silently diverge',()=>{const plan=fixture();plan.pins[0].source='printed';assert.throws(()=>connectorExportItems(plan),/passen nicht/);assert.throws(()=>buildConnectorGuide(parts,plan.connections,plan),/stimmen nicht/);const missing=fixture();missing.pins.pop();assert.throws(()=>connectorExportItems(missing),/zwei/);assert.throws(()=>buildConnectorGuide(parts,missing.connections,missing),/genau zwei/);});
test('legacy printed pin geometry remains included',()=>{const plan=fixture();delete plan.connections[0].pin.source;for(const p of plan.pins){delete p.source;p.vertices=[0,0,0,1,0,0,0,1,0];p.triangles=[0,1,2];}const output=connectorExportItems(plan);assert.equal(output.printablePins.length,2);assert.deepEqual(output.purchasedPins,[]);assert.equal(buildConnectorGuide(parts,plan.connections,plan).pinFiles.length,2);});
test('deeper child hole retains the actual centered pin ends and at least the specified end clearance',()=>{const plan=fixture();plan.connections[0].hole.depthChild=8;const guide=buildConnectorGuide(parts,plan.connections,plan),p=guide.steps[1].views.points[0];assert.deepEqual(p.pinEnds,[[0,0,-5],[0,0,5]]);assert.equal(p.childHole.bottom[2]-p.pinEnds[1][2],3);});
