import test from 'node:test';import assert from 'node:assert/strict';import Module from 'manifold-3d';import {Matrix4} from 'three';import {detectSeams,cutSeam,autoSeams,markPart} from '../src/features.mjs';import {fromSolid,validate,bestOrientation,bounds} from '../src/engine.mjs';import {assemblyData,threeMF} from '../src/guide.mjs';import {unzipSync,strFromU8} from 'fflate';
const api=await Module();api.setup();
test('curved surface contour cuts through a hollow wall and conserves volume',async()=>{const {surfacePatch,cutSurfacePatch}=await import('../src/features.mjs');const {smartRegion}=await import('../src/engine.mjs');const outer=api.Manifold.sphere(100,48),inner=api.Manifold.sphere(90,48),shell=outer.subtract(inner),data=fromSolid(shell);outer.delete();inner.delete();shell.delete();const selection=smartRegion(data,0,35,60),preview=surfacePatch(data,selection.faces,20);assert.ok(preview.walls.triangles.length>0);const pieces=cutSurfacePatch(api,data,selection.faces,20);assert.ok(pieces.length>=2);pieces.forEach(p=>assert.ok(validate(api,p).volume>0));assert.ok(Math.abs(pieces.reduce((s,p)=>s+p.volume,0)-data.volume)<2);});
function roof(){const lower=api.Manifold.cylinder(40,80,60,48),upper=api.Manifold.cylinder(60,50,15,48),moved=upper.translate([0,0,40]),solid=lower.add(moved);const data=fromSolid(solid);lower.delete();upper.delete();moved.delete();solid.delete();return data;}
test('closed roof-ring edges are detected and cut with volume preservation',()=>{const data=roof(),seams=detectSeams(data,20,50);assert.ok(seams.length>=2);let result;for(const s of seams){try{result=cutSeam(api,data,s);break;}catch{}}assert.ok(result,'At least one ring must be separable');assert.equal(result.length,2);result.forEach(d=>assert.ok(validate(api,d).volume>0));assert.ok(Math.abs(result.reduce((s,p)=>s+p.volume,0)-data.volume)<1);});
test('automatic edge cutting creates closed parts',()=>{const data=roof(),result=autoSeams(api,data,{angle:20,minPerimeter:50,maxCuts:3});assert.ok(result.cuts>=1);result.parts.forEach(p=>assert.ok(validate(api,p).volume>0));});
test('engraved IDs remove material without opening the part',()=>{const solid=api.Manifold.cube([100,80,20]),d=fromSolid(solid);solid.delete();const marked=markPart(api,d,{text:'T001',point:[50,40,20],normal:[0,0,1],size:8,depth:.7,rotation:0,emboss:false});assert.ok(marked.volume<d.volume);assert.ok(marked.volume>d.volume*.99);assert.ok(validate(api,marked).volume>0);});
test('raised IDs add material and remain connected',()=>{const solid=api.Manifold.cube([100,80,20]),d=fromSolid(solid);solid.delete();const marked=markPart(api,d,{text:'T002',point:[50,40,20],normal:[0,0,1],size:8,depth:.7,rotation:30,emboss:true});assert.ok(marked.volume>d.volume);});
test('disconnected labels are rejected before constructing loose glyph bodies',()=>{const solid=api.Manifold.cube([100,80,20]),d=fromSolid(solid);solid.delete();assert.throws(()=>markPart(api,d,{text:'T002',point:[500,400,200],normal:[0,0,1],size:8,depth:.7,rotation:0,emboss:true}),/Schrift passt hier nicht/);});
test('print orientation can be reversed for the assembly illustration',()=>{const d=roof(),oriented=bestOrientation(d,[200,200,100]),matrix=new Matrix4().fromArray(oriented.transform).invert().toArray(),restored=assemblyData({...oriented,assemblyMatrix:matrix});const before=bounds(d),after=bounds(restored);before.min.forEach((v,i)=>assert.ok(Math.abs(v-after.min[i])<.001));before.max.forEach((v,i)=>assert.ok(Math.abs(v-after.max[i])<.001));});
test('3MF contains matching colors, IDs and solid meshes',()=>{const d=roof(),zip=unzipSync(threeMF([{...d,id:'T001',color:'#12abef'}])),xml=strFromU8(zip['3D/3dmodel.model']);assert.match(xml,/displaycolor="#12abefFF"/);assert.match(xml,/name="T001"/);assert.match(xml,/<triangle /);assert.ok(zip['_rels/.rels']);});
