import test from 'node:test';
import assert from 'node:assert/strict';
import {BoxGeometry,CylinderGeometry,RingGeometry,Matrix4,Vector3,Quaternion} from 'three';
import {selectInterior,autoMarkLocations} from '../src/interior-marking.mjs';
import {transformData} from '../src/engine.mjs';
function box(x=100,y=80,z=4){const g=new BoxGeometry(x,y,z);return{vertices:new Float32Array(g.attributes.position.array),triangles:new Uint32Array(g.index.array),id:'T001'};}
function seed(mesh,normal){const a=new Vector3(),b=new Vector3(),c=new Vector3(),n=new Vector3(...normal);for(let f=0;f<mesh.triangles.length/3;f++){a.fromArray(mesh.vertices,mesh.triangles[f*3]*3);b.fromArray(mesh.vertices,mesh.triangles[f*3+1]*3);c.fromArray(mesh.vertices,mesh.triangles[f*3+2]*3);if(b.sub(a).cross(c.sub(a)).normalize().dot(n)>.999)return f;}throw Error('No matching face');}
const interior=(mesh,normal=[0,0,-1])=>({data:selectInterior(mesh,seed(mesh,normal)).region});
function shell(radius=300){const outer=new CylinderGeometry(radius,radius,80,64,1,true),inner=new CylinderGeometry(radius-3,radius-3,80,64,1,true),bottom=new RingGeometry(radius-3,radius,64),top=new RingGeometry(radius-3,radius,64);bottom.rotateX(Math.PI/2).translate(0,-40,0);top.rotateX(-Math.PI/2).translate(0,40,0);const vertices=[],triangles=[];for(const [index,g] of [outer,inner,bottom,top].entries()){const offset=vertices.length/3;vertices.push(...g.attributes.position.array);for(let f=0;f<g.index.array.length;f+=3){const [a,b,c]=g.index.array.slice(f,f+3);triangles.push(offset+a,offset+(index===1?c:b),offset+(index===1?b:c));}}return{vertices:new Float32Array(vertices),triangles:new Uint32Array(triangles),id:'T002',interiorSeed:outer.index.array.length/3,innerFaces:inner.index.array.length/3};}
function approx(a,b,tol=1e-6){assert.ok(Math.abs(a-b)<=tol,`${a} ≈ ${b}`);}
test('interior selection grows across coplanar slab triangles and stops at sharp edges',()=>{const data=box(),selection=selectInterior(data,seed(data,[0,0,-1]),35);assert.equal(selection.faces.length,2);assert.equal(selection.region.triangles.length,6);for(let i=2;i<selection.region.vertices.length;i+=3)approx(selection.region.vertices[i],-2);assert.equal(selection.fraction,1/6);});
test('curved selection grows with the slider but does not wrap around the sheet',()=>{const data=shell(),small=selectInterior(data,data.interiorSeed,20),selection=selectInterior(data,data.interiorSeed,60);assert.ok(small.faces.length<selection.faces.length);assert.ok(selection.faces.length<data.innerFaces/2);assert.ok(selection.faces.every(f=>f>=data.interiorSeed&&f<data.interiorSeed+data.innerFaces));});
test('additional inner seeds combine without selecting the outside',()=>{const data=shell(),seeds=Array.from({length:4},(_,i)=>({seed:data.interiorSeed+i*32,angle:60}));const selection=selectInterior(data,seeds[0].seed,60,seeds);assert.equal(selection.faces.length,data.innerFaces);assert.ok(selection.faces.every(f=>f>=data.interiorSeed&&f<data.interiorSeed+data.innerFaces));});
test('automatic ID lies on the allowed side and keeps all original geometry untouched',()=>{const data=box(),result=autoMarkLocations([data],interior(data)),out=result.parts[0];assert.equal(result.assigned,1);assert.equal(result.unassigned,0);assert.deepEqual(result.failed,[]);assert.strictEqual(out.vertices,data.vertices);assert.strictEqual(out.triangles,data.triangles);assert.equal(out.interiorRegion.triangles.length,6);assert.equal(out.plannedMark.text,'T001');assert.equal(out.plannedMark.autoId,true);assert.equal(out.plannedMark.emboss,false);approx(out.plannedMark.point[2],-2);assert.ok(new Vector3(...out.plannedMark.normal).distanceTo(new Vector3(0,0,-1))<1e-9);assert.equal(data.plannedMark,undefined);assert.equal(data.interiorRegion,undefined);});
test('automatic interior ID survives print rotation and translation',()=>{const original=box(),matrix=new Matrix4().makeTranslation(70,80,90).multiply(new Matrix4().makeRotationY(.7)),part={...transformData(original,matrix),id:'T017'},result=autoMarkLocations([part],interior(original),{rotation:20});assert.equal(result.assigned,1);const mark=result.parts[0].plannedMark,sourcePoint=new Vector3(...mark.point).applyMatrix4(matrix.clone().invert()),expectedNormal=new Vector3(0,0,-1).transformDirection(matrix);approx(sourcePoint.z,-2,1e-5);assert.ok(new Vector3(...mark.normal).distanceTo(expectedNormal)<1e-5);assert.equal(mark.text,'T017');const baseline=new Vector3(Math.cos(mark.rotation*Math.PI/180),Math.sin(mark.rotation*Math.PI/180),0).applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0,0,1),new Vector3(...mark.normal))).transformDirection(matrix.clone().invert()),expected=new Vector3(1,0,0).applyAxisAngle(new Vector3(0,0,-1),20*Math.PI/180);assert.ok(baseline.distanceTo(expected)<1e-5);const region=result.parts[0].interiorRegion;let area=0;for(let f=0;f<region.triangles.length;f+=3){const [a,b,c]=[0,1,2].map(k=>new Vector3().fromArray(region.vertices,region.triangles[f+k]*3));area+=b.sub(a).cross(c.sub(a)).length()/2;}approx(area,8000,.002);for(let i=0;i<region.vertices.length;i+=3){const p=new Vector3().fromArray(region.vertices,i).applyMatrix4(matrix.clone().invert());assert.ok(Math.abs(p.x)<=50.00001&&Math.abs(p.y)<=40.00001);approx(p.z,-2,1e-5);}});
test('thin wall fails instead of allowing engraving through the opposite skin',()=>{const data=box(100,80,.5),result=autoMarkLocations([data],interior(data),{depth:.6});assert.equal(result.assigned,0);assert.equal(result.unassigned,1);assert.match(result.failed[0].reason,/Keine sichere/);assert.equal(result.parts[0].plannedMark,undefined);assert.ok(result.parts[0].interiorRegion);});
test('small face cannot fit even the reduced font size',()=>{const data=box(3,3,4),result=autoMarkLocations([data],interior(data));assert.equal(result.assigned,0);assert.equal(result.unassigned,1);assert.match(result.failed[0].reason,/Schrift/);});
test('parts outside the selected interior report unplaceable and clear stale regions',()=>{const data=box(),far={...transformData(data,new Matrix4().makeTranslation(200,0,0)),transform:undefined,id:'T003',interiorRegion:interior(data).data},result=autoMarkLocations([far],interior(data));assert.equal(result.assigned,0);assert.equal(result.unassigned,1);assert.match(result.failed[0].reason,/Keine ausgewählte Innenseite/);assert.equal(result.parts[0].interiorRegion,undefined);});
test('hollow curved part can receive an ID on its allowed interior only',()=>{const data=shell(),selected=selectInterior(data,data.interiorSeed),result=autoMarkLocations([data],{data:selected.region},{size:4});assert.equal(result.assigned,1);const mark=result.parts[0].plannedMark;assert.ok(mark.normal[0]*mark.point[0]+mark.normal[2]*mark.point[2]<0,'Normal faces the interior cavity');assert.equal(mark.size,4);assert.equal(result.parts[0].interiorRegion.triangles.length,selected.region.triangles.length);});
test('missing selection and invalid parameters fail explicitly',()=>{assert.throws(()=>autoMarkLocations([box()],null),/Innenseite/);assert.throws(()=>selectInterior(box(),-1),/Innenseite/);assert.throws(()=>selectInterior(box(),0,90),/Auswahlweite/);assert.throws(()=>autoMarkLocations([box()],interior(box()),{depth:9}),/einstellungen/);});

