import test from 'node:test';import assert from 'node:assert/strict';import {Matrix4} from 'three';import {unionInteriorRegions,restoreInteriorSelection,transferInteriorSelection} from '../src/mark-locations.mjs';
const triangle=(x=0)=>({vertices:new Float32Array([x,0,0,x+1,0,0,x,1,0]),triangles:new Uint32Array([0,1,2])});
function faceKeys(region){return Array.from({length:region.triangles.length/3},(_,f)=>Array.from({length:3},(_,k)=>Array.from(region.vertices.slice(region.triangles[f*3+k]*3,region.triangles[f*3+k]*3+3)).join(',')).sort().join('|')).sort();}
test('extending a loaded mask preserves every old triangle and deduplicates overlapping selections',()=>{const a=triangle(),b=triangle(2),base=unionInteriorRegions(a,b),addition=unionInteriorRegions(a,triangle(4)),combined=unionInteriorRegions(base,addition);assert.equal(combined.triangles.length/3,3);for(const face of faceKeys(base))assert.ok(faceKeys(combined).includes(face));assert.deepEqual(faceKeys(base),faceKeys(unionInteriorRegions(base,base)));});
test('different nearby surfaces are never tolerance-snapped or deleted when selection masks unite',()=>{const a=triangle(),b=triangle(1e-5),combined=unionInteriorRegions(a,b);assert.equal(combined.triangles.length,6);assert.equal(combined.vertices.length,18);});
test('legacy projects restore the entire chosen mask as immutable base without inventing seed indices',()=>{const mesh=triangle(),saved={...mesh,interiorRegion:mesh};const restored=restoreInteriorSelection(saved,mesh);assert.equal(restored.interiorRegion.triangles.length,3);assert.equal(restored.interiorBaseRegion,restored.interiorRegion);assert.deepEqual(restored.interiorSeeds,[]);assert.equal(restored.interiorSeed,undefined);});
test('future seed lists remain editable only when validation preserves the exact geometry layout',()=>{const mesh=unionInteriorRegions(triangle(),triangle(2)),saved={...mesh,interiorRegion:mesh,interiorSeeds:[{seed:0,angle:35},{seed:1,angle:60}],interiorSeed:1,interiorAngle:60};const unchanged=restoreInteriorSelection(saved,mesh);assert.deepEqual(unchanged.interiorSeeds,saved.interiorSeeds);assert.equal(unchanged.interiorBaseRegion,undefined);const reordered={...mesh,triangles:new Uint32Array([...mesh.triangles.slice(3),...mesh.triangles.slice(0,3)])};const safe=restoreInteriorSelection(saved,reordered);assert.deepEqual(safe.interiorSeeds,[]);assert.deepEqual(faceKeys(safe.interiorBaseRegion),faceKeys(mesh));});
test('saved base and new seeds roundtrip together without freezing away slider editing',()=>{const base=triangle(),mask=unionInteriorRegions(base,triangle(2)),mesh=mask,saved={...mesh,interiorRegion:mask,interiorBaseRegion:base,interiorSeeds:[{seed:1,angle:35}],interiorSeed:1};const restored=restoreInteriorSelection(saved,mesh);assert.deepEqual(restored.interiorSeeds,saved.interiorSeeds);assert.deepEqual(faceKeys(restored.interiorBaseRegion),faceKeys(base));assert.equal(restored.interiorRegion.triangles.length,6);});
test('stale and malformed seed metadata falls back to exact saved region',()=>{const mesh=triangle(),saved={...mesh,interiorRegion:mesh,interiorSeeds:[{seed:500,angle:60}]};const restored=restoreInteriorSelection(saved,mesh);assert.deepEqual(restored.interiorSeeds,[]);assert.deepEqual(faceKeys(restored.interiorRegion),faceKeys(mesh));});
test('orientation moves both base and effective mask while geometry changes freeze all selected surfaces',()=>{const base=triangle(),region=unionInteriorRegions(base,triangle(2)),part={interiorRegion:region,interiorBaseRegion:base,interiorSeeds:[{seed:1,angle:60}],interiorSeed:1,interiorAngle:60},matrix=new Matrix4().makeTranslation(0,0,10).toArray();const moved=transferInteriorSelection(part,matrix);assert.equal(moved.interiorRegion.vertices[2],10);assert.equal(moved.interiorBaseRegion.vertices[2],10);assert.equal(moved.interiorSeeds.length,1);const changed=transferInteriorSelection(part,matrix,false);assert.equal(changed.interiorBaseRegion,changed.interiorRegion);assert.equal(changed.interiorRegion.triangles.length,6);assert.deepEqual(changed.interiorSeeds,[]);});

test('known saved area count is retained as metadata and includes additions when frozen after reordering',()=>{const base=triangle(),mesh=unionInteriorRegions(base,triangle(2)),saved={...mesh,interiorRegion:mesh,interiorBaseRegion:base,interiorBaseRegionCount:22,interiorSeeds:[{seed:1,angle:35}],interiorSeed:1};assert.equal(restoreInteriorSelection(saved,mesh).interiorBaseRegionCount,22);const reordered={...mesh,triangles:new Uint32Array([...mesh.triangles.slice(3),...mesh.triangles.slice(0,3)])};assert.equal(restoreInteriorSelection(saved,reordered).interiorBaseRegionCount,23);assert.equal(transferInteriorSelection(saved,null,false).interiorBaseRegionCount,23);});
