import test from 'node:test';import assert from 'node:assert/strict';
import Module from 'manifold-3d';import {Vector3,Matrix4,Quaternion,BoxGeometry} from 'three';
import {referenceTextFrame} from '../src/mark-alignment.mjs';
import {fromSolid,transformData} from '../src/engine.mjs';
import {autoMarkLocations,selectInterior} from '../src/interior-marking.mjs';
import {textMesh,markPart} from '../src/features.mjs';
import {restoreMarkLocation} from '../src/mark-locations.mjs';
const api=await Module();api.setup();
const baseline=mark=>new Vector3(Math.cos(mark.rotation*Math.PI/180),Math.sin(mark.rotation*Math.PI/180),0).applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0,0,1),new Vector3(...mark.normal)));
function visibleCenter(mark){const u=baseline(mark),n=new Vector3(...mark.normal),v=n.clone().cross(u),label=textMesh(mark.text,mark.point,mark.normal,mark.size,mark.depth,mark.rotation),min=[Infinity,Infinity],max=[-Infinity,-Infinity],point=new Vector3();for(let i=0;i<label.vertices.length;i+=3){point.fromArray(label.vertices,i);for(const [j,axis]of [u,v].entries()){const q=point.dot(axis);min[j]=Math.min(min[j],q);max[j]=Math.max(max[j],q);}}return u.multiplyScalar((min[0]+max[0])/2).addScaledVector(v,(min[1]+max[1])/2).addScaledVector(n,new Vector3(...mark.point).dot(n));}
function upper(data){const a=new Vector3(),b=new Vector3(),c=new Vector3();for(let f=0;f<data.triangles.length/3;f++){a.fromArray(data.vertices,data.triangles[f*3]*3);b.fromArray(data.vertices,data.triangles[f*3+1]*3);c.fromArray(data.vertices,data.triangles[f*3+2]*3);if(b.sub(a).cross(c.sub(a)).normalize().z>.999)return selectInterior(data,f);}throw Error('No upper face');}
test('common model X projects consistently through arbitrary print rotations',()=>{const pose=new Matrix4().makeRotationX(.8).multiply(new Matrix4().makeRotationZ(-.4)).setPosition(40,50,60);for(const sourceNormal of [[0,0,1],[0,0,-1],[.3,.8,.5],[-.2,.7,-.8]]){const n=new Vector3(...sourceNormal).normalize(),printNormal=n.clone().transformDirection(pose),frame=referenceTextFrame(printNormal,{transform:pose}),mark={normal:printNormal.toArray(),rotation:frame.rotation},actual=baseline(mark).transformDirection(pose.clone().invert()),expected=new Vector3(1,0,0).projectOnPlane(n).normalize();assert.ok(actual.distanceTo(expected)<1e-9);}});
test('a normal parallel to model X falls back deterministically to model Y',()=>{for(const n of [[1,0,0],[-1,0,0]]){const frame=referenceTextFrame(n);assert.equal(frame.usedFallback,true);assert.ok(frame.u.distanceTo(new Vector3(0,1,0))<1e-9);}});
test('a transformed parent reference still points along the complete model X',()=>{const parentAssembly=new Matrix4().makeRotationY(.8).multiply(new Matrix4().makeRotationZ(.4)),sourceNormal=new Vector3(0,0,-1),sourceReference=new Vector3(1,0,0).transformDirection(parentAssembly.clone().invert()),frame=referenceTextFrame(sourceNormal,{referenceDirection:sourceReference.toArray(),fallbackDirection:new Vector3(0,1,0).transformDirection(parentAssembly.clone().invert()).toArray()}),actual=frame.u.clone().transformDirection(parentAssembly),assemblyNormal=sourceNormal.clone().transformDirection(parentAssembly);assert.ok(actual.distanceTo(new Vector3(1,0,0).projectOnPlane(assemblyNormal).normalize())<1e-9);});
test('complete same-size numbers are centered on the inner surface in both print poses',()=>{const sourceSolid=api.Manifold.cube([100,80,4]),source=fromSolid(sourceSolid),mask=upper(source).region,halves=sourceSolid.splitByPlane([1,0,0],50),poses=[new Matrix4().makeRotationY(.7).setPosition(40,70,90),new Matrix4().makeRotationZ(-.6).multiply(new Matrix4().makeRotationX(.4)).setPosition(-20,80,30)],parts=halves.map((solid,i)=>({...transformData({...fromSolid(solid),cutPlanes:[{normal:[1,0,0],offset:50}]},poses[i]),id:String(i+1)})),result=autoMarkLocations(parts,{data:mask});assert.equal(result.assigned,2);for(let i=0;i<2;i++){const p=result.parts[i],mark=p.plannedMark,inv=poses[i].clone().invert(),u=baseline(mark).transformDirection(inv),center=visibleCenter(mark).applyMatrix4(inv);assert.ok(u.distanceTo(new Vector3(1,0,0))<1e-5);assert.equal(mark.depth,.4);assert.equal(mark.size,8);assert.ok(center.distanceTo(new Vector3(i===0?75:25,40,4))<1e-4);const engraved=markPart(api,p,mark);assert.ok(engraved.volume<p.volume||engraved.volume<halves[i].volume());}halves.forEach(s=>s.delete());sourceSolid.delete();});
test('tessellation density does not pull the automatic label away from the area center',()=>{const geometry=new BoxGeometry(100,80,4,13,3,1),data={vertices:new Float32Array(geometry.attributes.position.array),triangles:new Uint32Array(geometry.index.array),id:'7'},result=autoMarkLocations([data],{data:upper(data).region});assert.equal(result.assigned,1);assert.ok(visibleCenter(result.parts[0].plannedMark).distanceTo(new Vector3(0,0,2))<1e-5);});
test('an impossible common size reports an open location instead of shrinking one number',()=>{const solid=api.Manifold.cube([8,8,4]),data={...fromSolid(solid),id:'8'},result=autoMarkLocations([data],{data:upper(data).region},{size:8});assert.equal(result.assigned,0);assert.equal(result.unassigned,1);assert.equal(result.parts[0].plannedMark,undefined);assert.match(result.failed[0].reason,/gemeinsame Schriftgröße 8 mm/);assert.equal(result.parts[0].plannedMarkIssue,result.failed[0].reason);solid.delete();});
test('manual rotation and explicit old depth are preserved while new defaults are 0.4 mm',()=>{const solid=api.Manifold.cube([100,80,4]),data=fromSolid(solid),mask=upper(data).region,manual={point:[50,40,4],normal:[0,0,1],text:'1',size:8,rotation:37,depth:.6,emboss:false,autoId:true,placement:'manual'},result=autoMarkLocations([{...data,id:'1',plannedMark:manual}],{data:mask});assert.strictEqual(result.parts[0].plannedMark,manual);assert.equal(result.parts[0].plannedMark.rotation,37);assert.equal(result.parts[0].plannedMark.depth,.6);assert.equal(restoreMarkLocation({...manual,depth:undefined}).depth,.4);const automatic=autoMarkLocations([{...data,id:'2'}],{data:mask});assert.equal(automatic.parts[0].plannedMark.depth,.4);solid.delete();});
test('safe curved glyphs are not rejected because their padded empty rectangle is less flat',()=>{
 const geometry=new BoxGeometry(40,40,4,80,1,1),positions=geometry.attributes.position.array;
 for(let i=0;i<positions.length;i+=3)if(positions[i+2]>0)positions[i+2]+=.003*positions[i]**2;
 const data={vertices:new Float32Array(positions),triangles:new Uint32Array(geometry.index.array),id:'39'},selected=upper(data),result=autoMarkLocations([data],{data:selected.region},{size:8,depth:.4});
 assert.equal(result.assigned,1);const mark=result.parts[0].plannedMark;assert.equal(mark.size,8);assert.equal(mark.depth,.4);
 const canonical=textMesh(mark.text,[0,0,0],[0,0,1],mark.size,mark.depth),xs=Array.from(canonical.vertices).filter((_,i)=>i%3===0),halfPaddedWidth=(Math.max(...xs)-Math.min(...xs)+2)/2;
 assert.ok(.003*halfPaddedWidth**2>.1,'old padded-rectangle flatness threshold would reject the central label');
 assert.ok(visibleCenter(mark).distanceTo(new Vector3(0,0,2))<.3,'fallback uses a central full-size label');
 assert.doesNotThrow(()=>markPart(api,data,mark));geometry.dispose();
});
