import test from 'node:test';import assert from 'node:assert/strict';
import Module from 'manifold-3d';import {Vector3,Matrix4} from 'three';
import {fromSolid,toSolid,transformData} from '../src/engine.mjs';
import {markPart,textMesh} from '../src/features.mjs';
import {validateMarkFootprint,validateMarkMaskCoverage} from '../src/mark-validation.mjs';
import {assignMarkLocations} from '../src/mark-locations.mjs';
import {autoMarkLocations,selectInterior,subsetSurface} from '../src/interior-marking.mjs';
const api=await Module();api.setup();
const settings=(extra={})=>({text:'T001.52',point:[50,40,4],normal:[0,0,1],size:8,depth:.6,rotation:0,emboss:false,placement:'manual',autoId:true,...extra});
function box(size=[100,80,4]){const solid=api.Manifold.cube(size),data=fromSolid(solid);solid.delete();return data;}
function face(data,normal){const a=new Vector3(),b=new Vector3(),c=new Vector3(),target=new Vector3(...normal);for(let f=0;f<data.triangles.length/3;f++){a.fromArray(data.vertices,data.triangles[f*3]*3);b.fromArray(data.vertices,data.triangles[f*3+1]*3);c.fromArray(data.vertices,data.triangles[f*3+2]*3);if(b.sub(a).cross(c.sub(a)).normalize().dot(target)>.999)return f;}throw Error('Missing face');}
test('manual half-label at a cut edge is rejected without changing source geometry',()=>{const data=box(),original=new Float32Array(data.vertices);assert.throws(()=>markPart(api,data,settings({point:[1,40,4]})),/vollständige Schrift.*Schnittkante/);assert.deepEqual(data.vertices,original);});
test('0.6 mm engraving cannot punch through a 0.5 mm wall even with open glyphs',()=>{const data=box([100,80,.5]);assert.throws(()=>markPart(api,data,settings({text:'T111',point:[50,40,.5]})),/Wand.*zu dünn/);});
test('the wall safety margin applies to every glyph, not only its anchor',()=>{const data=box([100,80,.7]);assert.throws(()=>markPart(api,data,settings({text:'T111',point:[50,40,.7]})),/mindestens 0,15 mm/);const thick=box([100,80,.8]),marked=markPart(api,thick,settings({text:'T111',point:[50,40,.8]}));assert.ok(marked.volume<thick.volume);});
test('all manual glyph contours must lie within the selected interior mask',()=>{const data=box(),mask={vertices:new Float32Array([40,30,4,60,30,4,40,50,4,60,50,4]),triangles:new Uint32Array([0,1,2,1,3,2])};assert.throws(()=>markPart(api,{...data,interiorRegion:mask},settings()),/außerhalb der gewählten Innenfläche/);});
test('a nearby mask on the opposite wall does not permit raised text on the outside',()=>{const data=box([100,80,.05]),mask=selectInterior(data,face(data,[0,0,-1])).region;assert.throws(()=>markPart(api,{...data,interiorRegion:mask},settings({text:'T111',point:[50,40,.05],emboss:true})),/gewählten Innenfläche/);});
test('valid engraving on a gently curved hollow inner wall stays connected',()=>{const outer=api.Manifold.cylinder(80,300,300,128),inner=api.Manifold.cylinder(80,297,297,128),shell=outer.subtract(inner),data=fromSolid(shell),a=new Vector3(),b=new Vector3(),c=new Vector3(),faces=[];for(let f=0;f<data.triangles.length/3;f++){a.fromArray(data.vertices,data.triangles[f*3]*3);b.fromArray(data.vertices,data.triangles[f*3+1]*3);c.fromArray(data.vertices,data.triangles[f*3+2]*3);const center=a.clone().add(b).add(c).multiplyScalar(1/3),normal=b.sub(a).cross(c.sub(a)).normalize();if(center.x*normal.x+center.y*normal.y<0&&Math.abs(normal.z)<.1)faces.push(f);}data.interiorRegion=subsetSurface(data,faces);const mark=settings({text:'T111',point:[297,0,40],normal:[-1,0,0],size:4}),marked=markPart(api,data,mark),solid=toSolid(api,marked),components=solid.decompose();assert.equal(components.length,1);assert.ok(marked.volume<data.volume);components.forEach(s=>s.delete());solid.delete();shell.delete();inner.delete();outer.delete();});
test('a preserved manual anchor is flagged after a split makes its final ID too wide',()=>{const source=box(),region=selectInterior(source,face(source,[0,0,1])).region,solid=toSolid(api,source),halves=solid.splitByPlane([1,0,0],50),parts=halves.map((s,i)=>({...fromSolid(s),id:`T001.${i+1}`})),mark=settings({point:[48,40,4],text:'T001.123'});assert.equal(assignMarkLocations(parts,[mark]).assigned,1);const result=autoMarkLocations(parts,{data:region},{generateMarks:false}),out=result.parts.find(p=>p.plannedMark);assert.deepEqual(out.plannedMark.point,mark.point);assert.equal(out.plannedMark.text,mark.text);assert.match(out.plannedMarkIssue,/Schrift passt/);assert.equal(result.invalidMarks.length,1);assert.throws(()=>markPart(api,out,out.plannedMark),/Schrift passt/);halves.forEach(s=>s.delete());solid.delete();});
test('final ID width is checked after transformed placement without moving a manual anchor',()=>{const source=box([20,80,4]),mark=settings({text:'T1',point:[10,40,4],size:5});const first=markPart(api,source,mark);assert.ok(first.volume<source.volume);const pose=new Matrix4().makeRotationY(.6).setPosition(20,30,40),oriented=transformData(source,pose);const region=selectInterior(source,face(source,[0,0,1])).region,parts=[{...oriented,id:'T001.123'}];assignMarkLocations(parts,[{...mark,text:'T001.123'}]);const before=structuredClone(parts[0].plannedMark),result=autoMarkLocations(parts,{data:region},{generateMarks:false});assert.deepEqual(result.parts[0].plannedMark,before);assert.equal(result.invalidMarks.length,1);});
test('valid final glyph coverage reports the retained material margin',()=>{const data=box(),mark=settings(),label=textMesh(mark.text,mark.point,mark.normal,mark.size,mark.depth);const checked=validateMarkFootprint(data,label,mark);assert.ok(checked.samples>100);assert.ok(checked.minRemaining>3.39);assert.ok(checked.maxDeviation<1e-6);});
test('exact selected-mask coverage catches a tiny unselected hole between footprint samples',()=>{const data=box(),vertices=[],triangles=[];for(const [x0,y0,x1,y1] of [[0,0,100,40.1201],[0,40.1401,100,80],[0,40.1201,50.1127,40.1401],[50.1327,40.1201,100,40.1401]]){const start=vertices.length/3;vertices.push(x0,y0,4,x1,y0,4,x1,y1,4,x0,y1,4);triangles.push(start,start+1,start+2,start,start+2,start+3);}data.interiorRegion={vertices:new Float32Array(vertices),triangles:new Uint32Array(triangles)};const mark=settings({text:'I'}),label=textMesh(mark.text,mark.point,mark.normal,mark.size,mark.depth);assert.equal(validateMarkFootprint(data,label,mark).valid,true,'sparse/tolerant surface checks alone do not prove full mask coverage');assert.throws(()=>markPart(api,data,mark),/Buchstabenkonturen.*Innenfläche/);});
test('mask validator never deletes native handles after a fatal WASM operation',()=>{const data=box();data.interiorRegion=selectInterior(data,face(data,[0,0,1])).region;const mark=settings({text:'1'}),label=textMesh(mark.text,mark.point,mark.normal,mark.size,mark.depth);for(const phase of ['construct','subtract','area']){let constructed=0,deleted=0;const fatal=new WebAssembly.RuntimeError('memory access out of bounds'),handle={area(){if(phase==='area')throw fatal;return 1;},subtract(){if(phase==='subtract')throw fatal;return handle;},delete(){deleted++;}},fake={CrossSection:{ofPolygons(){if(++constructed===2&&phase==='construct')throw fatal;return handle;}}};assert.throws(()=>validateMarkMaskCoverage(fake,data,label,mark),error=>error===fatal);assert.equal(deleted,0,phase);}});
test('a fatal delete stops cleanup before touching further native mask handles',()=>{const data=box();data.interiorRegion=selectInterior(data,face(data,[0,0,1])).region;const mark=settings({text:'1'}),label=textMesh(mark.text,mark.point,mark.normal,mark.size,mark.depth);let count=0,deleted=[];const fatal=new WebAssembly.RuntimeError('unreachable'),handles=[0,1,2].map(i=>({area:()=>i===2?0:1,subtract:()=>handles[2],delete(){deleted.push(i);if(i===0)throw fatal;}})),fake={CrossSection:{ofPolygons:()=>handles[count++]}};assert.throws(()=>validateMarkMaskCoverage(fake,data,label,mark),error=>error===fatal);assert.deepEqual(deleted,[0]);});
