import {Box3,Vector3,BufferGeometry,BufferAttribute,Ray,DoubleSide} from 'three';
import {MeshBVH} from 'three-mesh-bvh';
import {clipTriangleByPrism} from './open-clip.mjs';

// Split the existing surface triangles through the complete cutter depth.
// No new closing faces and no solid boolean are generated by this preview.
export function throughSurfacePlan(data,proposals,progress=()=>{}){
 const geometry=new BufferGeometry();geometry.setAttribute('position',new BufferAttribute(data.vertices,3));geometry.setIndex(new BufferAttribute(data.triangles,1));
 const tree=new MeshBVH(geometry,{indirect:true}),owner=new Int32Array(data.triangles.length/3).fill(-1),replacements=new Map();
 const groups=proposals.map(()=>({faces:[],fragments:[]}));
 const triangle=f=>Array.from({length:3},(_,k)=>Array.from(data.vertices.subarray(data.triangles[f*3+k]*3,data.triangles[f*3+k]*3+3)));
 try{proposals.forEach((proposal,i)=>{
  const d=proposal.cutDefinition;if(!d)return;const box=new Box3(),xs=d.contours.flat().map(p=>p[0]),ys=d.contours.flat().map(p=>p[1]);
  for(const x of [Math.min(...xs),Math.max(...xs)])for(const y of [Math.min(...ys),Math.max(...ys)])for(const z of [d.min,d.max])box.expandByPoint(new Vector3(...d.u).multiplyScalar(x).addScaledVector(new Vector3(...d.v),y).addScaledVector(new Vector3(...d.n),z));box.expandByScalar(.001);
  progress(`Durchgehende offene Vorschau: Kontur ${i+1}/${proposals.length}`);
  tree.shapecast({intersectsBounds:b=>box.intersectsBox(b),intersectsTriangle:(_,f)=>{
   if(owner[f]>=0)return false;const previous=replacements.get(f),input=previous||[triangle(f)],inside=[],outside=[];
   for(const tri of input){const split=clipTriangleByPrism(tri,d);inside.push(...split.inside);outside.push(...split.outside);}
   if(!inside.length)return false;
   if(!previous&&!outside.length){groups[i].faces.push(f);owner[f]=i;}else{groups[i].fragments.push(...inside);if(outside.length)replacements.set(f,outside);else{owner[f]=i;replacements.delete(f);}}
   return false;
  }});
 });
 const rest={faces:[],fragments:[]};for(let f=0;f<owner.length;f++)if(owner[f]<0){const pieces=replacements.get(f);if(pieces)rest.fragments.push(...pieces);else rest.faces.push(f);}groups.push(rest);
 return groups.map((g,i)=>{
  if(!g.faces.length&&!g.fragments.length)return null;const vertices=[],triangles=[],lookup=new Map();
  for(const f of g.faces)for(let k=0;k<3;k++){const source=data.triangles[f*3+k];let index=lookup.get(source);if(index===undefined){index=vertices.length/3;lookup.set(source,index);vertices.push(...data.vertices.subarray(source*3,source*3+3));}triangles.push(index);}
  for(const tri of g.fragments)for(const p of tri){triangles.push(vertices.length/3);vertices.push(...p);}
  return {vertices:new Float32Array(vertices),triangles:new Uint32Array(triangles),proposal:i<proposals.length?i:null,unassigned:i===proposals.length};
 }).filter(Boolean);
 }finally{geometry.dispose();}
}
// Extend each contour prism only as far as the wall behind its selected surface.
// The ray starts just inside that surface, so distant opposite roof sides are not deliberately included.
export function extendThroughWall(data,proposals){
 const geometry=new BufferGeometry();geometry.setAttribute('position',new BufferAttribute(data.vertices,3));geometry.setIndex(new BufferAttribute(data.triangles,1));const tree=new MeshBVH(geometry,{indirect:true}),a=new Vector3(),b=new Vector3(),c=new Vector3();
 try{for(const proposal of proposals){const d=proposal.cutDefinition;if(!d)continue;const n=new Vector3(...d.n),direction=n.clone().negate(),step=Math.max(1,Math.ceil(proposal.faces.length/32));let count=0,min=d.min;
  for(let i=0;i<proposal.faces.length;i+=step){const f=proposal.faces[i];a.fromArray(data.vertices,data.triangles[f*3]*3);b.fromArray(data.vertices,data.triangles[f*3+1]*3);c.fromArray(data.vertices,data.triangles[f*3+2]*3);const normal=b.clone().sub(a).cross(c.clone().sub(a)).normalize();if(normal.dot(n)<.3)continue;const origin=a.clone().add(b).add(c).multiplyScalar(1/3).addScaledVector(n,-.02);const hit=tree.raycastFirst(new Ray(origin,direction),DoubleSide);if(hit&&hit.face.normal.dot(direction)>.1){min=Math.min(min,hit.point.dot(n)-.3);count++;}}
  d.min=min;proposal.wallProbeCount=count;
 }}finally{geometry.dispose();}return proposals;
}
